// <auto-generated />
namespace iRoloDex.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class DBsetup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DBsetup));
        
        string IMigrationMetadata.Id
        {
            get { return "202010292304359_DB setup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
